# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('url', models.SlugField()),
            ],
            options={
                'verbose_name_plural': 'companies',
            },
        ),
    ]
