version: '2'
services:
  database:
    image: mysql:latest
    container_name: mysql-django
    ports:
      - "4407:3306"
    env_file: .env-mysql
  web:
    build: .
    image: reasonmljobs:1.0
    container_name: django
    command: ./run-production.sh
    volumes:
      - .:/code
    ports:
      - "8000:80"
    links:
      - database
    env_file: .env